
- name: Windows Test
  hosts: windows
  gather_facts: false
  vars:
    ansible_user: ansibleuser1
    ansible_port: 5986
    ansible_connection: winrm
    ansible_winrm_transport: certificate
    ansible_winrm_ca_trust_path: "{{ lookup('env', 'MY_CACERT_FILE') }}"
    ansible_winrm_cert_pem: "{{ lookup('env', 'MY_CERT_FILE') }}"
    ansible_winrm_cert_key_pem: "{{ lookup('env', 'MY_KEY_FILE') }}"
    ansible_winrm_server_cert_validation: ignore
  tasks:
    - name: Ping Server
      ansible.windows.win_ping:
      