---
- name: Windows Test
  hosts: windows
  tasks:
    # - name: Ping Server
    #   ansible.windows.win_ping:
    - name: test file
      # ansible.builtin.command: cat "{{ lookup('env', 'MY_CERT_FILE') }}"
      debug:
        msg:
          - "Cert Path: {{ lookup('env', 'MY_CERT_FILE') }}"
          - "Key Path: {{ lookup('env', 'MY_KEY_FILE') }}"
        
      
