---
- name: Windows Test
  hosts: localhost
  vars:
    cert_path: "{{ lookup('env', 'MY_CERT_FILE') }}"
  tasks:
    # - name: Ping Server
    #   ansible.windows.win_ping:
    - name: test file
      # ansible.builtin.command: cat "{{ lookup('env', 'MY_CERT_FILE') }}"
      debug:
        msg:
          - "Cert Path: {{ lookup('env', 'MY_CERT_FILE') }}"
          - "Key Path: {{ lookup('env', 'MY_KEY_FILE') }}"
        
    - name: check contents of cert file 
      ansible.builtin.command: cat "{{ cert_path }}"
      register: cert_content

    - name: print cert content
      debug:
        msg: 
          - "{{ cert_content }}"
      
