---
- name: Windows Test
  hosts: localhost
  tasks:
    # - name: Ping Server
    #   ansible.windows.win_ping:
    - name: test file
      ansible.builtin.command: cat "{{ lookup('env', 'MY_CERT_FILE') }}"
        
      
